# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Debug'
  buildPlatform: 'Any CPU'
  continueOnError: true
stages:
  - stage: CI
    displayName: CI/CD of eschool
    jobs:
       - job: Build
         steps:
            - task: ArchiveFiles@2
              displayName: Archive Static Files
              inputs:
                  rootFolderOrFile: '$(build.sourcesDirectory)'
                  archiveType: 'zip'
                  replaceExistingArchive: true
                  includeRootFolder: false
            - task: PublishBuildArtifacts@1
              inputs:
                PathtoPublish: '$(build.sourcesDirectory)/$(Build.BuildId).zip'
                ArtifactName: 'CloudSigma'
                publishLocation: 'Container'

       - job: CD
         dependsOn: Build
       - deployment: VMDeploy
         displayName: Deploy to VM
         environment: 
                name: CloudSigma
                resourceType: VirtualMachine
                tags: dev, web # only deploy to virtual machines with this tag
         strategy:
                runOnce:
                  deploy:   
                      steps:
                      - task: DownloadPipelineArtifact@2
                        inputs:
                          buildType: 'current'
                          artifactName: 'CloudSigma'
                          targetPath: '$(Pipeline.Workspace)'

                      - task: IISWebAppManagementOnMachineGroup@0
                        continueOnError: false 
                        displayName: IISWebAppManage
                        inputs:
                           IISDeploymentType: 'IISWebsite'
                           ActionIISWebsite: 'CreateOrUpdateWebsite'
                           WebsiteName: 'Default Web Site'
                           WebsitePhysicalPath: 'C:\contentful\Deployment'
                           WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
                          
                      - task: IISWebAppDeploymentOnMachineGroup@0
                        continueOnError: false 
                        displayName: IISWebAppDeploy
                        inputs:
                              WebSiteName: 'Default Web Site'
                              VirtualApplication: 'CloudSigma'
                              Package: '$(System.DefaultWorkingDirectory)/CloudSigma/$(Build.BuildId).zip'
                              TakeAppOfflineFlag: true
                              XmlVariableSubstitution: true 
                      

