# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Debug'
  buildPlatform: 'Any CPU'
  continueOnError: true
stages:
  - stage: Build
    displayName: Build
    jobs:
       - job:
         steps:
            
            - task: ArchiveFiles@2
              inputs:
                  rootFolderOrFile: '$(build.sourcesDirectory)/$(Build.BuildId).zip'
                  archiveType: 'zip'
                  replaceExistingArchive: true
                  includeRootFolder: false
            - task: PublishBuildArtifacts@1
              inputs:
                PathtoPublish: '$(build.sourcesDirectory)/$(Build.BuildId).zip'
                ArtifactName: 'CloudSigma'
                publishLocation: 'Container'

       - job:
       - deployment: VMDeploy
         displayName: Deploy to VM
         environment: 
                name: CloudSigma
                resourceType: VirtualMachine
                tags: dev, web # only deploy to virtual machines with this tag
         strategy:
                runOnce:
                  deploy:   
                      steps:
                      - task: DownloadPipelineArtifact@2
                        inputs:
                          buildType: 'current'
                          artifactName: 'CloudSigma'
                          targetPath: '$(Pipeline.Workspace)'
                      

