# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Debug'
  buildPlatform: 'Any CPU'
  continueOnError: true
stages:
  - stage: CI
    displayName: CI/CD of eschool
    jobs:
       - job: Build
         steps:
            - task: CopyFiles@2
              inputs:
                SourceFolder: '$(Build.SourcesDirectory)'
                Contents: '**'
                TargetFolder: '$(Build.ArtifactStagingDirectory)'
            - task: ArchiveFiles@2
              displayName: Archive Static Files
              inputs:
                  rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
                  archiveType: 'zip'
                  archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
                  replaceExistingArchive: true
                  includeRootFolder: false
            - task: PublishBuildArtifacts@1
              inputs:
                PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
                ArtifactName: 'IqraT1.e-school'
                publishLocation: 'Container'
