# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Debug'
  buildPlatform: 'Any CPU'
  continueOnError: true
stages:
  - stage: CI
    displayName: CI/CD of eschool
    jobs:
       - job: Build
         steps:
            - task: CopyFiles@2
              inputs:
                SourceFolder: '$(Build.SourcesDirectory)'
                Contents: '**'
                TargetFolder: '$(Build.ArtifactStagingDirectory)'
            - task: ArchiveFiles@2
              displayName: Archive Static Files
              inputs:
                  rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
                  archiveType: 'zip'
                  archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
                  replaceExistingArchive: true
                  includeRootFolder: false
            - task: PublishBuildArtifacts@1
              inputs:
                PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
                ArtifactName: 'IqraT1.e-school'
                publishLocation: 'Container'

       - job: 
       - deployment: VMDeploy
         dependsOn: Build
         displayName: Deploy to VM
         environment: 
                name: CloudSigma
                resourceType: VirtualMachine
                tags: dev, web # only deploy to virtual machines with this tag
         strategy:
                runOnce:
                  deploy:   
                      steps:
                      - task: IISWebAppManagementOnMachineGroup@0
                        continueOnError: false 
                        displayName: IISWebAppManage
                        inputs:
                           IISDeploymentType: 'IISWebsite'
                           ActionIISWebsite: 'CreateOrUpdateWebsite'
                           WebsiteName: 'ESchool'
                           WebsitePhysicalPath: 'C:\ESchool\Deployment'
                           WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
                          
                      - task: IISWebAppDeploymentOnMachineGroup@0
                        continueOnError: false 
                        displayName: IISWebAppDeploy
                        inputs:
                              WebSiteName: 'ESchool'
                              VirtualApplication: 'CloudSigma'
                              Package: '$(System.DefaultWorkingDirectory)/_IqraT1.e-school/IqraT1.e-school/*.zip'
                              TakeAppOfflineFlag: true
                              XmlVariableSubstitution: true 
                      

   
